workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Initialize iOS directory
        script: |
          flutter build ios --config-only
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
      - name: Build IPA with Automatic Signing
        script: |
          flutter build ipa --release \
            --export-options-plist=/tmp/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
