workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Initialize iOS
        script: |
          flutter build ios --config-only
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
      - name: Build Flutter for iOS
        script: |
          # نستخدم --no-codesign عشان نمنع Xcode من البحث عن شهادات أثناء البناء
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
